spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:animaladoption};encrypt=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${SERVER_PORT:8080}
  tomcat:
    max-http-request-size: 50MB

# Nasza własna konfiguracja aplikacji
app:
  security:
    # Klucz do funkcji "Zapamiętaj mnie"
    remember-me-key: ${REMEMBER_ME_KEY}
    # Klucz do szyfrowania wrażliwych danych w bazie (zawsze 16, 24 lub 32 znaki dla AES)
    crypto-key: ${CRYPTO_KEY}